import HeaderApp from '@/components/layouts/HeaderApp'
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'hamo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className='bg-base-200'>
      <div className='bg-base-100'>
        <HeaderApp />
      </div>
      <div className="container-app drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content p-4">          
          {children}
        </div> 
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" aria-label="close sidebar" className="drawer-overlay"></label> 
          <ul className="menu p-4 w-80 min-h-full text-base-content space-y-4 [&>li>a]:p-3">
            {
            [4,3,2,6,7,5].map(e=> (
              <li key={e}>
                <Link href="/">
                  <svg className="h-5 w-5 text-primary-500" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round" data-testid="svg-icon">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 7m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                    <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                  </svg>
                  Home
                </Link>
              </li>
              ))
            }
          </ul>
      </div>
      </div>
    </section>
  )
}
